const CONSTANTS = {
  URL: 'https://magic-marks-api.vercel.app',
  // URL: 'http://localhost:5000',
  LOGIN__MODAL: 'LOGIN__MODAL',
  LOGOUT__MODAL: 'LOGOUT__MODAL',
  REGISTRATION__MODAL: 'REGISTRATION__MODAL',
  MARKS__MODAL: 'MARKS__MODAL',
  MARKS_DELETE__MODAL: 'MARKS_DELETE__MODAL',
  ERROR__MODAL: 'ERROR__MODAL',
  DEFAULT__LANG: 'ru',
  LANG__EN: 'en',
  TOKEN_EXPIRATION_TIME: 1800,
};

export default CONSTANTS;
